spring.application.name=SpringBootFlow

server.address=0.0.0.0
allowed-origins=${ALLOWED_ORIGINS}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



